name: science_go
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fpdart: ^1.1.0
  logger: ^2.0.1
  flutter_screenutil: ^5.9.0
  get: ^4.6.5
  image_picker: ^1.0.2
  model_viewer_plus: ^1.7.0
  awesome_dialog: ^3.1.0
  auto_size_text: ^3.0.0
  appwrite: ^11.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  ar_flutter_plugin:
    git:
      url: https://github.com/ahzam-shahnil/ar_flutter_plugin.git
      ref: raw-depth
  path_provider: ^2.1.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_gen_runner:
flutter_gen:
  integrations:
    flare_flutter: false
    flutter_svg: true
    rive: false
  line_length: 80
  output: lib/gen/
  colors:
    enabled: false

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/logos/
    - assets/ar_models/
    - Models/Chicken_01/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
